---
- name: Install gstreamer packages
  become: yes
  dnf:
    name:
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-bad-free-wildmidi
      - gstreamer1-plugins-bad-free-zbar
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-good-gtk
      - gstreamer1-plugins-good-qt
      - gstreamer1-plugins-base
      - gstreamer1-plugin-openh264
      - gstreamer1-libav
    state: present

- name: Install lame
  become: yes
  dnf:
    name: lame
    state: present

- name: Install ffmpeg
  become: yes
  dnf:
    name:
      - ffmpeg
      - ffmpeg-devel
      - ffmpeg-libs
    state: present

- name: Install multimedia group
  become: yes
  dnf:
    name: '@Multimedia'
    state: present
